apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: movie-ui-pod
      labels:
        app: movie-ui-app
        type: front-end

    spec:
      containers:
      - name: movie-ui-container
        image: juan2203/movie-ui:latest

  replicas: 3