apiVersion: v1 
kind: Service

metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
  - targetPort: 3030
    port: 80
    nodePort: 30008
  selector:
    app: movie-ui-app
    type: front-end
